#!/usr/bin/perl -w

=head
Utility to query regarding a bonded interface
author= <ankzzdev>AT<gmail.com>
bugs!! Any ??? I don't hope so!
Wish me to add a few more options, sure mail me!!
Utilize this code for usage. :-P Don't blame if 
something does not works out. Just shoot a mail.
License: I will get one
=cut

use strict;
use warnings;
use File::Basename;

# To support command line options
use Getopt::Long qw(:config no_ignore_case);

my $module =fileparse($0);
my $moduleversion = "1.03";

# My variables; Lets the module speak out loud
my $verbose = 0;

# Alas!! I hope you do not need to use this
my $debug = 0;
my $really = 0;

# B-) Directory
my $BOND="/proc/net/bonding/";

my $out="default";

# Utility method
sub trim($)
{
    my $string = shift;
    $string =~ s/^\s+//;
    $string =~ s/\s+$//;
    return $string;
}

sub dumpit($)
{
    return unless $debug eq 1 and $really eq 1;
    my $param = shift;
    return unless defined $param;
    use Data::Dumper;
    print STDOUT Dumper(\$param);
}

sub get_bonded_interfaces {

    return undef unless -d $BOND;

    opendir (DIR, $BOND) or return undef;

    my @bonds = ();
    while (my $file = readdir(DIR)) {
        next if $file eq "." or $file eq "..";
        push @bonds,$file;
    }
  
    print STDOUT "Bonds: ", join(' ',@bonds) ,"\n";

    return \@bonds;
}

sub get_inf_speed_in_mbps($$) {
    my $speed = shift;
    my $unit = shift;

    if( $unit eq "Kbps" ) {
       $speed /= 1000;
    }
    if( $unit eq "Gbps" ) {
       $speed *= 1000;
    }

    return $speed;
}

sub normalize_speed_unit($$) {
    my $speed = shift;
    my $unit = shift;

    if($speed >= 1000) {
       $speed /= 1000;
       $unit = "Gbps";
    }
    elsif ($speed <= 1) {
       $speed *= 1000;
       $unit = "Kbps";
    }
    return $speed." ".$unit;
}

sub get_bond_capabilityi($) {
    my $inf = shift;

    return undef unless defined $inf;

    my %cap = ();

    my @status = `cat $BOND$inf 2>/dev/null`;

    unless ( defined $status[0] ) {
        print STDOUT "Invalid bond name\n";
        return;
    }
    print STDOUT @status,"\n" if $debug eq 1;

    my $prefix="";
    my $slave_count =0;
    my $bond_speed=0;
    my $bond_speed_unit="Mbps";

    foreach my $line (@status) {

        print STDOUT "I:",$line,"\n" if $debug eq 1;

        my ($key,$value) = split(":",$line, 2);
        $key = trim($key);
        $value = trim($value) if defined $value;

        next if $key eq "";

        print STDOUT $key,":",$value,"\n" if $debug eq 1;

        # Parse the output
        if ( $line =~ m/Slave Interface/ ) {
            $prefix="Slave ";
            $slave_count++;
        }

        if( $prefix eq "Slave " ) {
            $cap{$prefix.$slave_count}{$key} = (defined $value)?$value:"NA";
            if ( $key =~ m/Speed/ ) {
                my ($speed,$unit) = split(" ",$value);
                $speed = int($speed);
                print STDOUT $cap{$prefix.$slave_count}{'Slave Interface'},": Speed: ",$speed.$unit,"\n" if $debug eq 1;
                $bond_speed += get_inf_speed_in_mbps($speed, $unit);
            }
        } else {
            $cap{$key} = (defined $value)?$value:"NA";
        }
    }
    $cap{slave_count} = $slave_count;
    $cap{speed} = normalize_speed_unit($bond_speed, $bond_speed_unit);
    dumpit(\%cap) if $debug eq 1;

    if ( $out eq 'default' ) {
      default_output(\%cap);
    } else {
      table_output($inf, \%cap);
    }
    return \%cap;
}

sub table_output($$) {
  my $inf = shift;
  my $inp = shift;

  return undef unless defined $inp;

  my %cap = %{$inp};

  print STDOUT "bond    |  slave  |  interface |  status  |  mode  |  queue-id  |  fail count  |  speed\n";
  my $size = keys %cap;
  my $cnt = $cap{"slave_count"};
  my $i=0;
  while ($i<$cnt) {
    $i++;
    print STDOUT $inf ;
    print STDOUT " " x (8 - length($inf));
    print STDOUT "|";

    print STDOUT "  $i";
    print STDOUT " " x (9 - (length("$i")+2));
    print STDOUT "|";

    my $sinf = $cap{"Slave $i"}{'Slave Interface'};

    $sinf = "Undefined" unless defined $sinf;

    print STDOUT "  $sinf";
    print STDOUT " " x (12 - (length($sinf)+2));
    print STDOUT "|";

    my $status = $cap{"Slave $i"}{'MII Status'};

    $status = "Unknown" unless defined $status;

    print STDOUT "  $status";
    print STDOUT " " x (10 - (length($status)+2));
    print STDOUT "|";

    my $mode = $cap{"Slave $i"}{'Duplex'};

    $mode = "Unknown" unless defined $mode;

    print STDOUT "  $mode";
    print STDOUT " " x (8 - (length($mode)+2));
    print "|";


    my $slaveId = $cap{"Slave $i"}{'Slave queue ID'};

    $slaveId = "Unknown" unless defined $slaveId;

    print STDOUT "  $slaveId";
    print STDOUT " " x (12 - (length($slaveId)+2));
    print STDOUT "|";

    my $failureCount = $cap{"Slave $i"}{'Link Failure Count'};

    $failureCount = "Unknown" unless defined $failureCount;
    print STDOUT "  $failureCount";
    print STDOUT " " x (14 - (length($slaveId)+2));
    print STDOUT "|";

    my $speed = $cap{"Slave $i"}{'Speed'};

    $speed = "Unknown" unless defined $speed;

    print STDOUT "  $speed";

    print STDOUT "\n";
  }
}

sub default_output($) {
  my $inp = shift;

  return undef unless defined $inp;

  my %cap = %{$inp};

  if ($verbose eq 1 ){
      while (my($key, $value) = each(%cap)){
          print STDOUT "    ".$key.": ".$value."\n" unless (ref($value) eq "HASH") ;
          if (ref($value) eq "HASH") {
             print "    ",$key," => \n";
             while (my($subkey, $val) = each(%{$value})){
                 print STDOUT "        ";
                 print STDOUT $subkey.": ".$val."\n" unless (ref($val) eq "HASH") ;
             }
          }
      }
  }
}

sub setOutMode() {
  my ($option, $value) = @_;

  OPTION : {
    $value eq 'default' and do {
      $out = 'default';
      last OPTION;
    };
    $value eq 'table' and do {
      $out = 'table';
      last OPTION;
    };
    do {
      print STDOUT "Invalid output (-o) option\n";
      print STDOUT "Only supported output options are: \n";
      print STDOUT "\tdefault\n";
      print STDOUT "\ttable\n";
      exit(-1);
    }
  }
}

sub Usage {
    print STDOUT "Usage:",$module," [OPTIONS] [COMMANDS]\n";
    print STDOUT "OPTIONS:\n";
    print STDOUT "         -o [default|table] : To set the output format\n";
    print STDOUT "         -d                 : To debug this tool\n";
    print STDOUT "         -v                 : To set verbose\n";
    print STDOUT "\n";
    print STDOUT "COMMANDS:\n";
    print STDOUT "         -i <bondname>: To list the specified bond's capability\n";
    print STDOUT "         -l           : To list all the bonds on the system\n";
    print STDOUT "         -s <bondname>: Get the bond Speed\n";
    print STDOUT "         -S <bondname>: Get status of bonded interface\n";
    print STDOUT "         -V           : Get the version of $module\n"
}

sub print_module_version()
{
  print STDOUT $module," version ",$moduleversion,"\n";
}

sub _get_bond_capability()
{
  print STDOUT "Called for @_\n" if $debug eq 1;

  my ($option, $value) = @_;

  OPTION : {
      $option eq 'i' and do {
         $verbose = 1;
         get_bond_capabilityi($value) if defined( $value );
         $verbose = 0;
         last OPTION;
      };
      $option eq 's' and do {
         my $cap = get_bond_capabilityi($value) if defined( $value );
         if (exists $cap->{'speed'}) {
          print STDOUT $value,": ",$cap->{'speed'},"\n";
         } else {
          print STDOUT $value,": Unknown (speed)\n"
         }
         last OPTION;
      };
      $option eq 'S' and do {
         my $cap = get_bond_capabilityi($value) if defined( $value );
         if (exists $cap->{'MII Status'}) {
          print STDOUT $value,": ",$cap->{'MII Status'},"\n";
         }else {
          print STDOUT $value,": Unknown (MII Status)\n"
         }
         last OPTION;
      };   
  }
}

sub main {
    if(@ARGV < 1) { Usage; return; }
    GetOptions ('h' => \&Usage, 'd' => \$debug, 'i=s' => \&_get_bond_capability,
                's=s' => \&_get_bond_capability, 'S=s' => \&_get_bond_capability,
                'l' => \&get_bonded_interfaces,
                'v' => \$verbose, 'V' => \&print_module_version,
                'o=s' => \&setOutMode
               );
}

main;
    
